# Generated by Django 5.2.17 on 2026-08-08 10:21

import django.core.validators
import django.db.models.deletion
import planner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('goal', models.CharField(max_length=160)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('people', models.PositiveIntegerField(default=0)),
                ('reward', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(default='사용자', max_length=40)),
                ('selected_character', models.CharField(default='owl', max_length=16)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('target_wake', models.TimeField(default='07:30')),
                ('target_sleep_minutes', models.PositiveSmallIntegerField(default=450)),
                ('latency_minutes', models.PositiveSmallIntegerField(default=24)),
                ('routine_minutes', models.PositiveSmallIntegerField(default=30)),
                ('adaptation_week', models.PositiveSmallIntegerField(default=1)),
                ('time_format', models.CharField(choices=[('12h', '12h'), ('24h', '24h')], default='24h', max_length=3)),
                ('alert_settings', models.JSONField(default=planner.models.default_alert_settings)),
                ('points', models.PositiveIntegerField(default=120)),
                ('group_streak', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('recruitment', '모집'), ('challenge', '도전'), ('season', '시즌')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(max_length=1000)),
                ('meta', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='planner.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fixed', 'fixed'), ('variable', 'variable')], max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('days', models.JSONField(blank=True, default=list)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('preparation_minutes', models.PositiveSmallIntegerField(default=0)),
                ('commute_minutes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='planner.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('status', models.CharField(choices=[('sleeping', 'sleeping'), ('alarm', 'alarm'), ('checking', 'checking'), ('complete', 'complete'), ('idle', 'idle')], default='sleeping', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to='planner.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PlanOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('offset_minutes', models.SmallIntegerField(default=0)),
                ('saved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_overrides', to='planner.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'target_date'), name='one_override_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('actual_sleep', models.TimeField()),
                ('actual_wake', models.TimeField()),
                ('freshness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sleepiness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('failure_reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='planner.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'date'), name='one_feedback_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='planner.challenge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to='planner.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'challenge'), name='one_challenge_join')],
            },
        ),
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google')], max_length=10)),
                ('connected', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to='planner.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'provider'), name='one_calendar_per_provider')],
            },
        ),
    ]
