# Generated by Django 5.2.17 on 2026-08-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconnection',
            name='selected_calendar_id',
            field=models.CharField(default='primary', max_length=255),
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='sync_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='source',
            field=models.CharField(choices=[('manual', 'manual'), ('google', 'google'), ('apple', 'apple')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='source',
            field=models.CharField(choices=[('manual', 'manual'), ('google', 'google'), ('apple', 'apple')], default='manual', max_length=10),
        ),
    ]
