# Generated by Django 5.2.17 on 2026-08-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_calendarconnection_selected_calendar_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='source',
        ),
    ]
