# Generated by Django 5.2.17 on 2026-08-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_sleep_adaptation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('recruitment', '모집'), ('challenge', '도전'), ('season', '시즌'), ('proof', '인증'), ('question', '질문'), ('free', '자유')], max_length=16),
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_comments', to='planner.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planner.communitypost')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='planner.communitypost')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='planner.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'profile'), name='one_post_like')],
            },
        ),
    ]
